# Generated by Django 6.1.1 on 2026-09-29 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0002_lead_leadactivity'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='leadactivity',
            options={'ordering': ['-created_at'], 'verbose_name': 'Lead Activity', 'verbose_name_plural': 'Lead Activities'},
        ),
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
    ]
