# Generated by Django 6.1.1 on 2026-09-29 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0003_alter_leadactivity_options_alter_user_managers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='source',
            field=models.CharField(choices=[('website', 'Website'), ('social-media', 'Social Media'), ('referral', 'Referral'), ('cold-call', 'Cold Call'), ('other', 'Other')], default='other', max_length=20),
        ),
    ]
